runtime: python39
env: standard
instance_class: F2 
automatic_scaling:
  max_instances: 1
entrypoint: gunicorn -b :$PORT src.api:app

handlers:
- url: /.*
  script: auto

runtime_config:
  python_version: 3
