runtime: python
env: flex

runtime_config:
    operating_system: "alpine"
    runtime_version: "3.12"

resources:
  cpu: 1
  memory_gb: 0.9

manual_scaling:
  instances: 1

entrypoint: gunicorn -b :$PORT src.api:app --timeout=120

handlers:
- url: /.*
  script: auto
